name: CI-coverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
    steps:

      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, json
          tools: phpunit
          coverage: pcov
          configuration: tests/phpunit.xml
          args: --coverage-clover

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-ansi --no-interaction --no-scripts --prefer-dist --optimize-autoloader

      - name: Test with phpunit
        run: vendor/bin/phpunit --configuration tests --coverage-clover coverage.xml
      env:
        COVERAGE_BADGE_PATH: 'coverage_dblmetaphone.svg'
        REPO_TOKEN: ${{ secrets.BADGES_TOKEN }}
        REPO: AGWD/badges
        REPORT: coverage.xml
        COMMIT_MESSAGE: updating badge
        COMMIT_NAME: github bot
        COMMIT_EMAIL: github-bot@adriangreen.com.au
      - name: generate coverage badge
        run: composer badge
